# -*- coding: utf-8 -*-
"""Day1 Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsow5Gr3xzmhQXfFeTg49Ww5_-QjZlw6

Import pandas

# 🐼 Introduction to Pandas (AI Data Play)

**Pandas** is the most popular library in Python used for **Data Analysis** and **Data Manipulation**.
Think of it as **"Excel for Python"**.

---

### 1. What is Pandas? 🧐
In Python, if you have a lot of data (like a list of names, prices, or dates), it is hard to manage using basic Python. Pandas gives you a special tool called a **DataFrame**.
*   **DataFrame:** A table with **Rows** and **Columns** (exactly like an Excel sheet).

---

### 2. Why do we use Pandas? 🚀
*   📂 **Read almost anything:** Can open CSV, Excel, SQL, and JSON files easily.
*   ⚡ **Handles Big Data:** Works very fast even with millions of rows where Excel might crash.
*   🧹 **Data Cleaning:** Real-world data is "messy." Pandas can find and fix missing values or errors using tools like `df.isnull()`.
*   📊 **Easy Math/Statistics:** Get the average, maximum, or summary of data with one line: `df.describe()`.
*   🔍 **Filtering & Sorting:** Instantly filter data (e.g., *"Show students with marks > 75"*).

---

### 📊 Comparison: Excel vs. Pandas

| Feature | Excel | Pandas (Python) |
| :--- | :--- | :--- |
| **Interface** | Visual (Click and point) | Code (Scripting) |
| **Speed** | Slow with large files | Extremely fast |
| **Automation** | Hard to repeat exactly | Run the same script 1000 times |
| **Complexity** | Good for basic math | Best for Advanced AI & Data Science |

---
"""

import pandas as pd

"""# 🐍 Python Basics: Lists & Dictionaries

Before learning Pandas, we need to understand how data is stored in Python using **Lists** and **Dictionaries**.

---

### 1. What is a List? `[ ]`
A **List** is an ordered collection of items. Think of it as a simple row of data.
*   **Syntax:** Uses square brackets `[ ]`.
*   **Example:** `['Amara', 'Bimal', 'Chathuri']`
*   **Key Feature:** Each item has a position called an **Index**.
    *   `Index 0` is Amara.
    *   `Index 1` is Bimal.

---

### 2. What is a Dictionary? `{ }`
A **Dictionary** stores data in **Key-Value** pairs. It is like a real dictionary where you look up a word (Key) to find its meaning (Value).
*   **Syntax:** Uses curly braces `{ }`.
*   **Example:** `{'Name': 'Amara', 'Age': 23}`
*   **Key Feature:** You use the **Key name** to get the data, not a number.

---

### 3. Understanding Your Data: "A Dictionary of Lists"
In your code, you combined both. This is the most common way to prepare data for Pandas.

```python
data = {
    'Name': ['Amara', 'Bimal', 'Chathuri'],
    'Age': [23, 25, 22]
}
"""

Data={
    'Name':['Nimal','Kamal','Sunil','Chathuri','Amali'],
    'Age':[25,21,23,24,22],
    'Marks':[86,78,89,91,87]
}

"""# ⚙️ Create CSV

Here is a simple breakdown of the actions performed by each line of code:

### 1. `df_temp = pd.DataFrame(data)`
*   **The Action:** It **converts** your raw data (the Dictionary) into a structured **Table**.
*   **How it works:** Pandas takes the "Keys" (Name, Age) and makes them **Column Headers**. It takes the "Lists" and makes them **Rows**.
*   **In Memory:** This table is now stored in the computer's memory under the name `df_temp`. Think of this like creating an Excel sheet inside Python.

---

### 2. `df_temp.to_csv('temp.csv', index=False)`
*   **The Action:** It **saves** the table as an actual file on your computer/Colab.
*   **`'temp.csv'`:** This is the name given to the new file.
*   **`index=False`:** By default, Pandas adds a column of row numbers (0, 1, 2...). `index=False` tells Python **"Don't save those extra numbers, just save my data."**
*   **Result:** You now have a physical file that you can open in Excel or Notepad.

---

### 💡 Summary
1.  **Line 1:** Creates a table **inside** the computer's memory.
2.  **Line 2:** Writes that table into a **physical file** on the disk.

*Note: You can replace `df_temp` with any name you like (e.g., `my_table`), as long as you use the same name in both lines.*
"""

mydata = pd.DataFrame(Data)
mydata.to_csv('temp.csv', index=False)
print(mydata)

"""# 📂 Loading and Viewing Data

Here is the explanation for the loading and previewing steps:

### 1. `df = pd.read_csv('filename.csv')`
*   **Action:** This line reads the CSV file from your storage.
*   **In Simple Terms:** It opens the file and converts it into a Pandas **DataFrame** (Table) named `df`.
*   **Analogy:** It's like opening an Excel workbook so you can start working on it.

### 2. `print(df.head())`
*   **Action:** Displays the first **5 rows** of your data.
*   **Why we use it:** Real-world data can have millions of rows. Printing all of them would crash your screen. `head()` helps you "peek" at the data to see if the columns and values look correct.
*   **Note:** If you want to see more rows, you can use `df.head(10)` to see 10 rows.

---
"""

show=pd.read_csv('temp.csv')
print(show.head(2))